language: c
matrix:
  include:
    - os: windows
    - os: osx
      osx_image: xcode11
      addons:
        homebrew:
          packages:
            - libusb-compat
    - os: linux
      addons:
        apt:
          packages:
            - libusb-dev
    - os: freebsd
      addons:
        pkg:
          packages:
            - gmake
            - zip
script: |-
    cd commandline
    case $TRAVIS_OS_NAME in
      linux)
         make
         ;;
      osx)
         make USBFLAGS=$(PKG_CONFIG_PATH=$(brew --prefix libusb-compat)/lib/pkgconfig pkg-config --cflags libusb) \
              USBLIBS="$(PKG_CONFIG_PATH=$(brew --prefix libusb-compat)/lib/pkgconfig pkg-config --libs libusb) -lusb"
         ;;
      windows)
         $MAKE USBLIBS=-lusb0
         EXE_EXT=.exe
         ;;
      freebsd)
         gmake
         ;;
    esac
    export ZIPFILE=micronucleus-${TRAVIS_CPU_ARCH}-${TRAVIS_OS_NAME}.zip
    zip ../$ZIPFILE micronucleus${EXE_EXT}

before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c \$\* --"
        export msys2+=" -msys2 -c \$\* --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain make mingw-w64-x86_64-libusb-win32
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        # taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it
        ;;
    esac

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "Micronucleus Buildbot"
      - git config --local user.email "autobuild@cloud"
      - if [ -z "${TRAVIS_TAG}" ]; then export TRAVIS_TAG=${TRAVIS_BRANCH}-LATEST; git tag $TRAVIS_TAG; fi

deploy:
  provider: releases
  api_key:
    secure: "zhJjg/5nkOYdSyYkvaPnBnMUKtybhhI0Hkj5zOTNwM8MKldGfMhmPd0fS0DphUfdaD/txsOVWbTpHC4Rt0gqSuUT9Ye7l/QLcyaOhuv4L8BNnAZfGMSeDi9bl7cDnW9hmmXTW/KXLm38LDNddy4EEC/AHBMwAcdPvDOTwfCdlT4gs28HHbOyFpCfU3AWJak1d3mM2BhoGVwLZlN+BZXy54QcZ7IadJTDxTAy2fo1hq92pi3dS822+DAa5PDezVzBsB1yVxuwwp0TABPtOfS3l4LBHsop//2d75ES2wLQVdpnL1FUGC2puYPiSTy5S16+1rL5wyj81YMPJbb1QFoRa07NBzu0EClP78yYAErRZ29TuWVD0varODegZZtmEoZ6eX26WVMZxrG4F00F8hKNU230E9mYkonGRvDf298nkyorwGJ+OMwMc3n+p8F7I2zYhV6UqqXmhHW9mZMMCxUnaZyuclVJ/tBybZE5ajIY4njA/QxwqRINu2enkkE6VWgtZD38tpcnmU2iSBUAqyxyJD7Z5RLZCiOoVssSii8rXVQplM/T5mWzrpdyjPkXRMdixG/fulrjG6SwSyQm5TgrpyVzP5+gfZFC3oeBbLM4x2TICQDpUGQMTAM6Zos7HZerjgZQwlmA8i+nQgBQ2gsy5JB+CZBnXhl5Oa4W92tf/tQ="
  file: "$ZIPFILE"
  overwrite: true
  skip_cleanup: true
  on:
      all_branches: true
      condition: "\"${TRAVIS_PULL_REQUEST}\" = false"

before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64
