language: c
script: cd commandline && make
os:
    - linux
    - osx
    - freebsd
    - windows
before_install:
- |-
    case $TRAVIS_OS_NAME in
      linux)
         sudo apt-get install -y libusb-dev
         ;;
      osx)
         brew install libusb
         ;;
    esac
