name: Build CLI tools

on:
  push:
    branches: [ gh-actions ]

jobs:
  build-all:
      strategy:
          matrix:
              os: [ ubuntu-latest, windows-2019, macos-latest ]
    runs-on: ${{ matrix.os }}
    env:
      BUILD_OS: ${{ runner.os }}
    steps:
    - name: install dependencies
      run: sudo sh -c "apt-get update && apt-get install libusb-dev"
      if: runner.os == "Linux"

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: git base-devel binutils mingw-w64-x86_64-toolchain make zip mingw-w64-x86_64-libusb-win32
        update: true
      if: runner.os == "Windows"

    - name: install dependencies
      run: brew install libusb-compat
      if: runner.os == "macOS"

    - uses: actions/checkout@v2
    - name: make
      run: sh -x $GITHUB_WORKSPACE/.github/workflows/build-pkg.sh
